from: node:0.12
services:
  - mongo:3.0:
      name: mongodb
      expose:
        - 27017:27017
      persist: false
tasks:
  env: env
  clean: rm -rf node_modules
  install: npm install
  test: npm run test
  lint: npm run lint
  build: npm run build